services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/prowlarr:/config
    ports:
      - 9696:9696/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/sonarr:/config
      - /volume1/data:/data
    ports:
      - 8989:8989/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always
  
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/lidarr:/config
      - /volume1/data:/data
    ports:
      - 8686:8686/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always   
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/radarr:/config
      - /volume1/data:/data
    ports:
      - 7878:7878/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/readarr:/config
      - /volume1/data/:/data
    ports:
      - 8787:8787/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - UMASK=022
    volumes:
      - /volume2/config/bazarr:/config
      - /volume1/data/:/data
    ports:
      - 6767:6767/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
    volumes:
      - /volume2/config/overseerr:/config
    ports:
      - 5055:5055/tcp
    network_mode: synobridge
    dns: #DNS Servers to help with speed issues some have
      - 9.9.9.9
      - 1.1.1.1
    security_opt:
      - no-new-privileges:true
    restart: always