x-common-config: &common-config
  environment:
    - PUID=1027
    - PGID=65536
    - TZ=Europe/London
    - UMASK=022
  network_mode: synobridge
  security_opt:
    - no-new-privileges:true
  restart: always

services:
  wg-ivpn:
    image: linuxserver/wireguard:legacy
    container_name: wg-ivpn
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/London
      - SERVERURL=auto # or explicit IVPN endpoint
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /volume2/config/wireguard:/config # place your wg0.conf here
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  test-ssh:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: test-vpn-ssh
    network_mode: 'service:wg-ivpn'
    environment:
      - SSH_PASSWORD=ChangeMe! # pick a strong one
    restart: unless-stopped

  prowlarr:
    <<: *common-config
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - /volume2/config/prowlarr:/config
    ports:
      - 9696:9696/tcp

  sonarr:
    <<: *common-config
    image: linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /volume2/config/sonarr:/config
      - /volume1/data:/data
    ports:
      - 8989:8989/tcp

  lidarr:
    <<: *common-config
    image: linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - /volume2/config/lidarr:/config
      - /volume1/data:/data
    ports:
      - 8686:8686/tcp

  radarr:
    <<: *common-config
    image: linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /volume2/config/radarr:/config
      - /volume1/data:/data
    ports:
      - 7878:7878/tcp

  readarr:
    <<: *common-config
    image: linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - /volume2/config/readarr:/config
      - /volume1/data:/data
    ports:
      - 8787:8787/tcp

  bazarr:
    <<: *common-config
    image: linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - /volume2/config/bazarr:/config
      - /volume1/data:/data
    ports:
      - 6767:6767/tcp

  overseerr:
    <<: *common-config
    image: linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - /volume2/config/overseerr:/config
    ports:
      - 5055:5055/tcp
    dns:
      - 9.9.9.9
      - 1.1.1.1
